arch: arm64
language: c
compiler: gcc
services:
  - docker
script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t evvvvan/theos-code-server:arm64 .
  - docker push evvvvan/theos-code-server:arm64
