arch: arm64
language: c
compiler: gcc
services:
  - docker
script:
  - docker pull evvvvan/theos-code-server:arm64
  - docker tag evvvvan/theos-code-server:arm64 registry.cn-hangzhou.aliyuncs.com/evan1s/theos-pi:latest
# - docker build -t registry.cn-hangzhou.aliyuncs.com/evan1s/theos-pi:latest .
after_success:
  - docker login --username=yangf1023@icloud.com -p=$aliyun_pwd registry.cn-hangzhou.aliyuncs.com
  - docker push registry.cn-hangzhou.aliyuncs.com/evan1s/theos-pi:latest
